/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rifle.gltf
Author: Armored Wave (https://sketchfab.com/armoredwave)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wz-96c-beryl-polish-army-service-rifle-a66248028448475f8287c914c0d235a7
Title: wz. 96C BERYL - Polish Army Service Rifle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rifle(props) {
  const { nodes, materials } = useGLTF('/rifle.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -8.42, 8.03]} rotation={[-Math.PI / 2, 0, 0]} scale={1000}>
            <mesh geometry={nodes.wz96C_transparent_magazine_M_Magazine_0.geometry} material={materials.M_Magazine} />
            <mesh geometry={nodes.wz96C_transparent_magazine_M_transparent_0.geometry} material={materials.M_transparent} />
          </group>
          <mesh geometry={nodes.gas_tube_cover_Material006_0.geometry} material={materials['Material.006']} rotation={[-Math.PI / 2, 0, 0]} scale={1000} />
          <mesh geometry={nodes.wz96C_body_Material007_0.geometry} material={materials['Material.007']} position={[0, 2.09, 9.41]} rotation={[-Math.PI / 2, 0, 0]} scale={1000} />
          <mesh geometry={nodes.wz96C_furniture_M_furniture_0.geometry} material={materials.M_furniture} position={[0, -1.01, 26.73]} rotation={[-Math.PI / 2, 0, 0]} scale={1000} />
          <mesh geometry={nodes.ammo_M_Magazine_0.geometry} material={materials.M_Magazine} position={[0.36, -13.46, 5.9]} rotation={[-1.57, 0, 0]} scale={1000} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rifle.gltf')
