/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 spider.gltf
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/fishing-spider-dolomedes-japonicas-03dd6e1052624bc4845c728c031bc8e8
Title: キクメハシリグモ 🕷 Fishing Spider, Dolomedes japonicas
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Spider(props) {
  const { nodes, materials } = useGLTF('/spider.gltf')
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[1.78, -0.47, -3.01]} scale={1} >
            <mesh geometry={nodes.Object_6.geometry} material={materials['QS1386-W21-1-9']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['QS1386-W21-1-9']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['QS1386-W21-1-9']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['QS1386-W21-1-9']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['QS1386-W21-1-9']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['QS1386-W21-1-9']} />
          </group>
          {/* <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-5.57, -0.01, -0.01]} rotation={[0.38, 1.57, -1.95]} scale={0.1} /> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spider.gltf')
